/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 room_uv.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room_uv.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 10, 82]} scale={[101, 10, 1]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.009']} position={[0, 10.58, 0]} scale={[0.4, 10.57, 0.4]} />
      <mesh geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[0, 21.33, 0]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.008']} position={[0.94, 21.75, 0]} scale={[0.1, 10, 10]} />
      <mesh geometry={nodes.Sphere005.geometry} material={nodes.Sphere005.material} position={[0, 21.33, 0]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.010']} position={[0, 10.58, 0]} scale={[0.4, 10.57, 0.4]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.010']} position={[0, 22.63, 0]} scale={[4.07, 2, 2]} />
    </group>
  )
}

useGLTF.preload('/room_uv.gltf')
